# Name of workflow
name: Lint and Test workflow

# Trigger workflow on all pull requests
on:
  pull_request:
    branches:
      - develop
      - staging

# Jobs to carry out
jobs:
  test:
    # Operating system to run job on
    runs-on: ubuntu-latest

    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Run lint
      - name: Run Lint
        run: npm run lint

      # Run build
      - name: Run Build
        run: npm run render-build

      # Run tests
      - name: Run Tests
        run: npm run test
